[package]
name = "ipc-test"
version = "0.1.0"
authors = ["David LeGare <dlegare.1001@gmail.com>"]

[dependencies]
amethyst = { version = "0.8" }
amethyst-editor-sync = { path = "../amethyst-editor-sync" }
env_logger = "0.5.13"
serde = { version = "1.0", features = ["derive"] }
